#include "../inc/qgsort.h"

int main(){
	int test[10] = {0, 3, 1, 2, 4, 9, 8, 7, 5, 6}, *a = load_big_data(10000), **b = load_100X100k(), color[10] = {0,1,2,0,1,2,2,1,0,0}, k;
	printf("\n\t100*100k数据排序：\n\n");
	clock_t start = clock();
	for (long i=0; i<100000; i++) insertSort(b[i], 100);
	printf("\t插入排序：耗时%dms。\n", clock()-start);
	free_100X100k(b);
	b = load_100X100k();
	start = clock();
	for (long i=0; i<100000; i++) MergeSort(b[i], 0, 100, NULL);
	printf("\t归并排序：耗时%dms。\n", clock()-start);
	free_100X100k(b);
	b = load_100X100k();
	start = clock();
	for (long i=0; i<100000; i++) QuickSort_Recursion(b[i], 0, 99);
	printf("\t快速排序（递归版）：耗时%dms。\n", clock()-start);
	free_100X100k(b);
	b = load_100X100k();
	start = clock();
	for (long i=0; i<100000; i++) QuickSort(b[i], 100);
	printf("\t快速排序（非递归版）：耗时%dms。\n", clock()-start);
	free_100X100k(b);
	b = load_100X100k();
	start = clock();
	for (long i=0; i<100000; i++) CountSort(b[i], 100, 32768);
	printf("\t计数排序：耗时%dms。\n", clock()-start);
	free_100X100k(b);
	b = load_100X100k();
	start = clock();
	for (long i=0; i<100000; i++) RadixCountSort(b[i], 100);
	printf("\t基数排序：耗时%dms。\n\n", clock()-start);
	free_100X100k(b);

	printf("\n\t10000数据排序：\n\n");
	start = clock();
	insertSort(a, 10000);
	printf("\t插入排序：耗时%dms。\n", clock()-start);
	free(a);
	a = load_big_data(10000);
	start = clock();
	MergeSort(a, 0, 10000, NULL);
	printf("\t归并排序：耗时%dms。\n", clock()-start);
	free(a);
	a = load_big_data(10000);
	start = clock();
	QuickSort_Recursion(a, 0, 9999);
	printf("\t快速排序（递归版）：耗时%dms。\n", clock()-start);
	free(a);
	a = load_big_data(10000);
	start = clock();
	QuickSort(a, 10000);
	printf("\t快速排序（非递归版）：耗时%dms。\n", clock()-start);
	free(a);
	a = load_big_data(10000);
	start = clock();
	CountSort(a, 10000, 32768);
	printf("\t计数排序：耗时%dms。\n", clock()-start);
	free(a);
	a = load_big_data(10000);
	start = clock();
	RadixCountSort(a, 10000);
	printf("\t基数排序：耗时%dms。\n\n", clock()-start);
	free(a);

	printf("\n\t50000数据排序：\n\n");
	a = load_big_data(50000);
	start = clock();
	insertSort(a, 50000);
	printf("\t插入排序：耗时%dms。\n", clock()-start);
	free(a);
	a = load_big_data(50000);
	start = clock();
	MergeSort(a, 0, 50000, NULL);
	printf("\t归并排序：耗时%dms。\n", clock()-start);
	free(a);
	a = load_big_data(50000);
	start = clock();
	QuickSort_Recursion(a, 0, 49999);
	printf("\t快速排序（递归版）：耗时%dms。\n", clock()-start);
	free(a);
	a = load_big_data(50000);
	start = clock();
	QuickSort(a, 50000);
	printf("\t快速排序（非递归版）：耗时%dms。\n", clock()-start);
	free(a);
	a = load_big_data(50000);
	start = clock();
	CountSort(a, 50000, 32768);
	printf("\t计数排序：耗时%dms。\n", clock()-start);
	free(a);
	a = load_big_data(50000);
	start = clock();
	RadixCountSort(a, 50000);
	printf("\t基数排序：耗时%dms。\n\n", clock()-start);
	free(a);

	printf("\n\t200000数据排序：\n\n");
	a = load_big_data(200000);
	start = clock();
	insertSort(a, 200000);
	printf("\t插入排序：耗时%dms。\n", clock()-start);
	free(a);
	a = load_big_data(200000);
	start = clock();
	MergeSort(a, 0, 200000, NULL);
	printf("\t归并排序：耗时%dms。\n", clock()-start);
	free(a);
	a = load_big_data(200000);
	start = clock();
	QuickSort_Recursion(a, 0, 199999);
	printf("\t快速排序（递归版）：耗时%dms。\n", clock()-start);
	free(a);
	a = load_big_data(200000);
	start = clock();
	QuickSort(a, 200000);
	printf("\t快速排序（非递归版）：耗时%dms。\n", clock()-start);
	free(a);
	a = load_big_data(200000);
	start = clock();
	CountSort(a, 200000, 32768);
	printf("\t计数排序：耗时%dms。\n", clock()-start);
	free(a);
	a = load_big_data(200000);
	start = clock();
	RadixCountSort(a, 200000);
	printf("\t基数排序：耗时%dms。\n\n", clock()-start);
	free(a);

	printf("\n\t颜色排序：\n\n\t排序前：");
	for (int i=0; i<10; i++) printf("%d\t",color[i]);
	printf("\n\t排序后：");
	ColorSort(color, 10);
	for (int i=0; i<10; i++) printf("%d\t",color[i]);

	printf("\n\n\n\t寻找第k大的数：\n\n\t排序前：");
	for (int i=0; i<10; i++) printf("%d\t",test[i]);
	printf("\n\t请输入k：");
	scanf("%d",&k);
	printf("\t第%d大的数为：%d\n\t排序后：", k, Find_K(test, 10, k));
	insertSort(test, 10);
	for (int i=0; i<10; i++) printf("%d\t",test[i]);
	printf("\n");
	system("pause");
	/*								//测试代码
	int *test = load_big_data(200000);
	RadixCountSort(test, 200000);
	for (int i=0; i<20; i++) printf("%d\t", test[i]);
	printf("\n");
	for (int i=199980; i<200000; i++) printf("%d\t", test[i]);
*/
}
